# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c26450df11a9051f532f3c1d83927ebdbef2daae540a5f092e20927a4b3c3ae8d6ca48fb9f042273f662fd67d5b5d6335956ee8243f364828fc9b54c9c3cfb2e

test:
  secret_key_base: 3440d9ef2c27c259fda85631f621b9e603244afe06cfd9a3af763357d4a4f8a5bd280f2a1e7a76b2bea4664fa9a91b51ca2d99e6ed003e2002c1a32f48370b5f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
